name: keg_generator
description: sql helper generator for simplified local database access.
topics:
  - codegen
  - sql
  - database

version: 0.1.3
repository: https://github.com/miyu1/keg/tree/main/keg_generator

resolution: workspace
#publish_to: none

environment:
  sdk: ">= 3.10.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer:  ^9.0.0
  build: ^4.0.4
  source_gen: ^4.2.0
  # path: ^1.9.0

  keg_annotation:

dev_dependencies:
  lints: 
  test:
  build_test: ^3.5.4
  path: ^1.9.1
  #sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  json_annotation: ^4.11.0
  