name: keg_annotation
description: annotations for keg_generator.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ">= 3.10.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.17.0
  # path: ^1.9.0

dev_dependencies:
  lints: 
  test: 
